language: cpp
compiler: gcc
sudo: required
dist: trusty

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - python
   - python-pip

before_script:
 - python --version
 - pip install --upgrade pip
 - pip install jinja2
 - pip install --egg SCons
 - python -v -c "import jinja2"
 - python2 -v -c "import jinja2"
 - which scons

# script: "python -v test.py"
script: "python -c \"import jinja2\""
